services:
  dns-monitor:
    image: dns-monitor:latest
    build:
      context: .
    container_name: dns-monitor
    environment:
      - DOMAIN=${DOMAIN}
      - NOTIFIER_TYPE=${NOTIFIER_TYPE}
      - PUSHOVER_APP_TOKEN=${PUSHOVER_APP_TOKEN}
      - PUSHOVER_USER_KEY=${PUSHOVER_USER_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_IDS=${TELEGRAM_CHAT_IDS}
      - DNS_SERVER=${DNS_SERVER}
      - CHECK_INTERVAL=${CHECK_INTERVAL}
      - NOTIFY_ON_ERRORS=${NOTIFY_ON_ERRORS}
      - CUSTOM_SUBDOMAINS=${CUSTOM_SUBDOMAINS}
      - CUSTOM_DKIM_SELECTORS=${CUSTOM_DKIM_SELECTORS}
    volumes:
      - ~/code/dns-monitor/data:/app/data:rw
    restart: unless-stopped